/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    DownloaderForm: typeof import('./src/components/DownloaderForm.vue')['default']
    DownloaderSettings: typeof import('./src/components/DownloaderSettings.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IAntDesignSettingOutlined: typeof import('~icons/ant-design/setting-outlined')['default']
    IPhCopyFill: typeof import('~icons/ph/copy-fill')['default']
    ITablerDownload: typeof import('~icons/tabler/download')['default']
    ITablerHome: typeof import('~icons/tabler/home')['default']
    ITablerRss: typeof import('~icons/tabler/rss')['default']
    ITablerSettings: typeof import('~icons/tabler/settings')['default']
    ITablerUser: typeof import('~icons/tabler/user')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemCol: typeof import('naive-ui')['NFormItemCol']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RssSettings: typeof import('./src/components/RssSettings.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    UserSettings: typeof import('./src/components/UserSettings.vue')['default']
  }
}
