// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/go-resty/resty/v2"
	"github.com/simonkimi/minebangumi/internal/app/config"
	"github.com/simonkimi/minebangumi/internal/app/repository"
	"github.com/simonkimi/minebangumi/internal/pkg/database"
	"github.com/simonkimi/minebangumi/pkg/mikan"
	"github.com/simonkimi/minebangumi/pkg/tmdb"
)

// Injectors from wire.go:

func InitializeManager() (Manager, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	httpxConfig := provideHttpXConfig(configConfig)
	httpX := NewHttpX(httpxConfig)
	v := provideTempClient(httpX)
	client := mikan.NewClient(v)
	tmdbConfig := provideTmdbConfig(configConfig, httpX)
	tmdbTmdb := tmdb.NewTmdb(tmdbConfig)
	db, err := database.NewDb()
	if err != nil {
		return nil, err
	}
	repo := repository.NewRepo(db)
	scraperService := newScraperService(tmdbTmdb)
	sourceService := newSourceService(client)
	apiProxyService := newApiProxyService(httpX)
	httpServiceConfig := provideHttpServiceConfig(configConfig)
	httpService := newHttpService(httpServiceConfig)
	manager := newManager(configConfig, httpX, client, tmdbTmdb, repo, scraperService, sourceService, apiProxyService, httpService)
	return manager, nil
}

// wire.go:

func provideHttpXConfig(conf config.Config) *HttpxConfig {
	return &HttpxConfig{
		ProxyEnabled:  conf.GetBool(config.ProxyEnabled),
		ProxyScheme:   conf.GetString(config.ProxyScheme),
		ProxyHost:     conf.GetString(config.ProxyHost),
		ProxyPort:     conf.GetString(config.ProxyPort),
		ProxyUsername: conf.GetString(config.ProxyUsername),
		ProxyPassword: conf.GetString(config.ProxyPassword),
	}
}

func provideTempClient(hx *HttpX) func() *resty.Client {
	return hx.GetTempClient
}

func provideTmdbConfig(conf config.Config, hx *HttpX) *tmdb.Config {
	return tmdb.NewConfig(conf.GetString(config.TmdbApiKey), hx.GetTempClient)
}

func provideHttpServiceConfig(conf config.Config) *HttpServiceConfig {
	return &HttpServiceConfig{
		Host: conf.GetString(config.ServerHost),
		Port: conf.GetInt(config.ServerPort),
	}
}
