// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/go-resty/resty/v2"
	"github.com/simonkimi/minebangumi/internal/app/config"
	"github.com/simonkimi/minebangumi/internal/app/repository"
	"github.com/simonkimi/minebangumi/internal/pkg/database"
	"github.com/simonkimi/minebangumi/pkg/mikan"
	"github.com/simonkimi/minebangumi/pkg/tmdb"
)

// Injectors from wire.go:

func InitializeManager() (*Manager, error) {
	service, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	httpxConfig := ProvideHttpXConfig(service)
	httpX := NewHttpX(httpxConfig)
	v := ProvideTempClient(httpX)
	client := mikan.NewClient(v)
	tmdbConfig := ProvideTmdbConfig(service, httpX)
	tmdbTmdb := tmdb.NewTmdb(tmdbConfig)
	db, err := database.NewDb()
	if err != nil {
		return nil, err
	}
	repo := repository.NewRepo(db)
	scraperService := newScraperService(tmdbTmdb)
	sourceService := newSourceService(client)
	manager := newManager(service, httpX, client, tmdbTmdb, repo, scraperService, sourceService)
	return manager, nil
}

// wire.go:

func ProvideHttpXConfig(conf *config.Service) *HttpxConfig {
	return &HttpxConfig{
		ProxyEnabled:  conf.GetBool(config.ProxyEnabled),
		ProxyScheme:   conf.GetString(config.ProxyScheme),
		ProxyHost:     conf.GetString(config.ProxyHost),
		ProxyPort:     conf.GetString(config.ProxyPort),
		ProxyUsername: conf.GetString(config.ProxyUsername),
		ProxyPassword: conf.GetString(config.ProxyPassword),
	}
}

func ProvideTempClient(hx *HttpX) func() *resty.Client {
	return hx.GetTempClient
}

func ProvideTmdbConfig(conf *config.Service, hx *HttpX) *tmdb.Config {
	return tmdb.NewConfig(conf.GetString(config.TmdbApiKey), hx.GetTempClient)
}
