// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIpv4Port():Promise<number>;

export function GetIpv6Port():Promise<number>;
