// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIpv4Port() {
  return window['go']['gui']['App']['GetIpv4Port']();
}

export function GetIpv6Port() {
  return window['go']['gui']['App']['GetIpv6Port']();
}
