// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package grmodel

type Mutation struct {
}

type ParseSourceInput struct {
	Source string `json:"source"`
	Parser string `json:"parser"`
}

type ParseSourceResponse struct {
	Title  *string   `json:"title,omitempty"`
	Files  []*string `json:"files,omitempty"`
	Season *int      `json:"season,omitempty"`
}

type Query struct {
}
