// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/parse": {
            "post": {
                "description": "Parse the source using the specified parser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parser"
                ],
                "summary": "Parse source",
                "parameters": [
                    {
                        "description": "Parse Source Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParseSourceForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ParseSourceResponse"
                        }
                    }
                }
            }
        },
        "/scrape": {
            "post": {
                "description": "Scrape the source using the specified scraper",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Scrape source",
                "parameters": [
                    {
                        "description": "Scrape Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ScrapeForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScrapeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ParseSourceForm": {
            "type": "object",
            "required": [
                "parser",
                "source"
            ],
            "properties": {
                "parser": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "api.ParseSourceResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "season": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.ScrapeForm": {
            "type": "object",
            "required": [
                "scraper",
                "title"
            ],
            "properties": {
                "language": {
                    "type": "string"
                },
                "scraper": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.ScrapeResponse": {
            "type": "object",
            "properties": {
                "background": {
                    "type": "string"
                },
                "first_air_year": {
                    "type": "string"
                },
                "original_title": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "poster_path": {
                    "type": "string"
                },
                "scraper": {
                    "type": "string"
                },
                "seasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ScrapeSeasonResponse"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.ScrapeSeasonResponse": {
            "type": "object",
            "properties": {
                "overview": {
                    "type": "string"
                },
                "poster": {
                    "type": "string"
                },
                "season_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
