definitions:
  api.LoginForm:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.TokenResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/proxy/poster:
    get:
      consumes:
      - application/json
      description: Retrieve a poster image based on the target type and target
      parameters:
      - description: Target type
        in: query
        name: target_type
        required: true
        type: string
      - description: Target
        in: query
        name: target
        required: true
        type: string
      produces:
      - image/jpeg
      - ' image/png'
      - ' image/gif'
      - ' image/webp'
      - ' image/bmp'
      - ' image/svg+xml'
      - ' image/jp2'
      responses:
        "200":
          description: poster image
          schema:
            type: file
      summary: Get poster image
      tags:
      - proxy
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login Form
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: Token
          schema:
            $ref: '#/definitions/api.TokenResponse'
      summary: User login
      tags:
      - user
swagger: "2.0"
