// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"strconv"
)

type ConfigResult struct {
	User *UserConfigResult `json:"user"`
}

type Mutation struct {
}

type ParseAcgSourceInput struct {
	Source string           `json:"source"`
	Parser SourceParserEnum `json:"parser"`
}

type ParseAcgSourceResult struct {
	Title  string   `json:"title"`
	Files  []string `json:"files"`
	Season int      `json:"season"`
}

type Query struct {
}

type ScrapeAcgResult struct {
	Scraper       ScraperEnum              `json:"scraper"`
	Title         string                   `json:"title"`
	OriginalTitle string                   `json:"originalTitle"`
	FirstAirDate  string                   `json:"firstAirDate"`
	Overview      string                   `json:"overview"`
	Poster        string                   `json:"poster"`
	Backdrop      string                   `json:"backdrop"`
	Seasons       []*ScrapeAcgSeasonResult `json:"seasons"`
}

type ScrapeAcgSeasonResult struct {
	SeasonID int    `json:"seasonId"`
	Title    string `json:"title"`
	Overview string `json:"overview"`
	Poster   string `json:"poster"`
}

type ScrapeAcgSourceInput struct {
	Title    string          `json:"title"`
	Scraper  ScraperEnum     `json:"scraper"`
	Language ScraperLanguage `json:"language"`
}

type UserConfigInput struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UserConfigResult struct {
	Username string `json:"username"`
	Token    string `json:"token"`
}

type APIStatusEnum string

const (
	APIStatusEnumSuccess              APIStatusEnum = "SUCCESS"
	APIStatusEnumInternalServerError  APIStatusEnum = "INTERNAL_SERVER_ERROR"
	APIStatusEnumNotFound             APIStatusEnum = "NOT_FOUND"
	APIStatusEnumUnauthorized         APIStatusEnum = "UNAUTHORIZED"
	APIStatusEnumUserCredentialsError APIStatusEnum = "USER_CREDENTIALS_ERROR"
	APIStatusEnumCancel               APIStatusEnum = "CANCEL"
	APIStatusEnumTimeout              APIStatusEnum = "TIMEOUT"
	APIStatusEnumThirdPartyAPIError   APIStatusEnum = "THIRD_PARTY_API_ERROR"
	APIStatusEnumBadRequest           APIStatusEnum = "BAD_REQUEST"
	APIStatusEnumFormValidationError  APIStatusEnum = "FORM_VALIDATION_ERROR"
)

var AllAPIStatusEnum = []APIStatusEnum{
	APIStatusEnumSuccess,
	APIStatusEnumInternalServerError,
	APIStatusEnumNotFound,
	APIStatusEnumUnauthorized,
	APIStatusEnumUserCredentialsError,
	APIStatusEnumCancel,
	APIStatusEnumTimeout,
	APIStatusEnumThirdPartyAPIError,
	APIStatusEnumBadRequest,
	APIStatusEnumFormValidationError,
}

func (e APIStatusEnum) IsValid() bool {
	switch e {
	case APIStatusEnumSuccess, APIStatusEnumInternalServerError, APIStatusEnumNotFound, APIStatusEnumUnauthorized, APIStatusEnumUserCredentialsError, APIStatusEnumCancel, APIStatusEnumTimeout, APIStatusEnumThirdPartyAPIError, APIStatusEnumBadRequest, APIStatusEnumFormValidationError:
		return true
	}
	return false
}

func (e APIStatusEnum) String() string {
	return string(e)
}

func (e *APIStatusEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = APIStatusEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApiStatusEnum", str)
	}
	return nil
}

func (e APIStatusEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ScraperEnum string

const (
	ScraperEnumTmdb ScraperEnum = "TMDB"
)

var AllScraperEnum = []ScraperEnum{
	ScraperEnumTmdb,
}

func (e ScraperEnum) IsValid() bool {
	switch e {
	case ScraperEnumTmdb:
		return true
	}
	return false
}

func (e ScraperEnum) String() string {
	return string(e)
}

func (e *ScraperEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScraperEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScraperEnum", str)
	}
	return nil
}

func (e ScraperEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ScraperLanguage string

const (
	ScraperLanguageZhHans ScraperLanguage = "Zh_HANS"
	ScraperLanguageZhHant ScraperLanguage = "Zh_HANT"
	ScraperLanguageJa     ScraperLanguage = "JA"
	ScraperLanguageEn     ScraperLanguage = "EN"
)

var AllScraperLanguage = []ScraperLanguage{
	ScraperLanguageZhHans,
	ScraperLanguageZhHant,
	ScraperLanguageJa,
	ScraperLanguageEn,
}

func (e ScraperLanguage) IsValid() bool {
	switch e {
	case ScraperLanguageZhHans, ScraperLanguageZhHant, ScraperLanguageJa, ScraperLanguageEn:
		return true
	}
	return false
}

func (e ScraperLanguage) String() string {
	return string(e)
}

func (e *ScraperLanguage) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScraperLanguage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScraperLanguage", str)
	}
	return nil
}

func (e ScraperLanguage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SourceParserEnum string

const (
	SourceParserEnumBangumi SourceParserEnum = "BANGUMI"
)

var AllSourceParserEnum = []SourceParserEnum{
	SourceParserEnumBangumi,
}

func (e SourceParserEnum) IsValid() bool {
	switch e {
	case SourceParserEnumBangumi:
		return true
	}
	return false
}

func (e SourceParserEnum) String() string {
	return string(e)
}

func (e *SourceParserEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourceParserEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourceParserEnum", str)
	}
	return nil
}

func (e SourceParserEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
